/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Vistas;

import Controlador.CMenuPrincipal;
import Controlador.IControlador;
import java.awt.Component;
import javax.swing.DefaultListModel;
import javax.swing.JList;
import javax.swing.JOptionPane;

/**
 *
 * @author DaCriPer
 */
public class VMenuCuadricula extends javax.swing.JFrame implements IVista{

    private String []dato;
    private final CMenuPrincipal controlador;
    DefaultListModel list;
    DefaultListModel listDos;
    /**
     * Creates new form MenuCuadricula
     * @param controlador
     */
    public VMenuCuadricula( IControlador controlador) {
        this.controlador = (CMenuPrincipal) controlador;
        initComponents();
        list = new DefaultListModel();
        listDos = new DefaultListModel();
        nuevoProductoList.setModel(list);
        nombreUsuarioVersion.setModel(listDos);
    }

    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        MiCuenta = new javax.swing.JButton();
        Categorias = new javax.swing.JButton();
        Vender = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        nuevoProductoList = new javax.swing.JList();
        jLabel2 = new javax.swing.JLabel();
        Actualizar = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        nombreUsuarioVersion = new javax.swing.JList();
        jMenuBar1 = new javax.swing.JMenuBar();
        Salir = new javax.swing.JMenu();
        Exit = new javax.swing.JMenuItem();
        MenuLista = new javax.swing.JMenu();
        VistaLista = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(153, 255, 255));

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel1.setText("Menu Principal");

        MiCuenta.setText("Mi Cuenta");
        MiCuenta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MiCuentaActionPerformed(evt);
            }
        });

        Categorias.setText("Categorias");
        Categorias.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CategoriasActionPerformed(evt);
            }
        });

        Vender.setText("Vender");
        Vender.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                VenderActionPerformed(evt);
            }
        });

        nuevoProductoList.setBackground(new java.awt.Color(153, 255, 255));
        jScrollPane2.setViewportView(nuevoProductoList);

        jLabel2.setText("Nuevos Productos");

        Actualizar.setText("Actualizar");
        Actualizar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ActualizarActionPerformed(evt);
            }
        });

        nombreUsuarioVersion.setBackground(new java.awt.Color(153, 255, 255));
        jScrollPane1.setViewportView(nombreUsuarioVersion);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(Actualizar, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(24, 24, 24))))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(19, 19, 19)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(Categorias)
                            .addComponent(MiCuenta))
                        .addGap(51, 51, 51)
                        .addComponent(Vender))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(67, 67, 67)
                        .addComponent(jLabel1)))
                .addContainerGap(63, Short.MAX_VALUE))
            .addComponent(jScrollPane1)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(Actualizar)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(Vender)
                            .addComponent(MiCuenta))
                        .addGap(30, 30, 30)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel2)
                            .addComponent(Categorias)))
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 28, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        Salir.setText("BuySell");
        Salir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SalirActionPerformed(evt);
            }
        });

        Exit.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_S, java.awt.event.InputEvent.CTRL_MASK));
        Exit.setText("Salir");
        Exit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ExitActionPerformed(evt);
            }
        });
        Salir.add(Exit);

        jMenuBar1.add(Salir);

        MenuLista.setText("View");
        MenuLista.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MenuListaActionPerformed(evt);
            }
        });

        VistaLista.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_L, java.awt.event.InputEvent.CTRL_MASK));
        VistaLista.setText("Menu lista");
        VistaLista.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                VistaListaActionPerformed(evt);
            }
        });
        MenuLista.add(VistaLista);

        jMenuBar1.add(MenuLista);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void MiCuentaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MiCuentaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_MiCuentaActionPerformed

    private void VenderActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_VenderActionPerformed
        // TODO add your handling code here:
        controlador.NuevoProducto();
    }//GEN-LAST:event_VenderActionPerformed

    private void CategoriasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CategoriasActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_CategoriasActionPerformed

    private void SalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SalirActionPerformed
        // TODO add your handling code here:
        ExitActionPerformed(evt);
    }//GEN-LAST:event_SalirActionPerformed

    private void MenuListaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MenuListaActionPerformed
        // cambiar de vista
        VistaListaActionPerformed(evt);
    }//GEN-LAST:event_MenuListaActionPerformed

    private void VistaListaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_VistaListaActionPerformed
        // TODO add your handling code here:
        controlador.CambiarVistaLista();
    }//GEN-LAST:event_VistaListaActionPerformed

    private void ExitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ExitActionPerformed
        // TODO add your handling code here:
        System.exit(0);
    }//GEN-LAST:event_ExitActionPerformed

    private void ActualizarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ActualizarActionPerformed
        // TODO add your handling code here:
        controlador.ActualizarNuevoproducto();
    }//GEN-LAST:event_ActualizarActionPerformed

    
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Actualizar;
    private javax.swing.JButton Categorias;
    private javax.swing.JMenuItem Exit;
    private javax.swing.JMenu MenuLista;
    private javax.swing.JButton MiCuenta;
    private javax.swing.JMenu Salir;
    private javax.swing.JButton Vender;
    private javax.swing.JMenuItem VistaLista;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JList nombreUsuarioVersion;
    private javax.swing.JList nuevoProductoList;
    // End of variables declaration//GEN-END:variables

    @Override
    public void noVisible() {
        this.setVisible(false);
    }
    
    @Override
    public void hacerVisible(){
        this.setVisible(true);
    }
    
    @Override
    public void ErrorUsuario() {
         
    }

    @Override
    public void ErrorContraseña() {
        
    }

    @Override
    public void ErrorDatos() {
         
    }

    @Override
    public void ConfirmarUsuario() {
        JOptionPane.showMessageDialog((Component) this, " OK ");
    }

    @Override
    public void colocarNuevoProducto(String s){
        list.clear();
        list.addElement(s);
    }
    
    @Override
    public void colocarIDUsuario(String idUsuario) {
        listDos.clear();
        listDos.addElement("-V. 1.0.0-   " + idUsuario   );
    }
}
