/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Vistas;

import Controlador.CMenuPrincipal;
import Controlador.IControlador;
import javax.swing.DefaultListModel;

/**
 *
 * @author DaCriPer
 */
public class VMenuLista extends javax.swing.JFrame implements IVista{

    private final CMenuPrincipal controlador;
    DefaultListModel list;

    /**
     * Creates new form Menu
     * @param controlador
     */
    public VMenuLista( IControlador controlador) {
        this.controlador = (CMenuPrincipal) controlador;
        initComponents();
        list = new DefaultListModel();
        nuevoProductoLista.setModel(list);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        MiCuenta = new javax.swing.JButton();
        Vender = new javax.swing.JButton();
        Categorias = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        nuevoProductoLista = new javax.swing.JList();
        jLabel2 = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        Salir = new javax.swing.JMenu();
        Exit = new javax.swing.JMenuItem();
        MenuCuadricula = new javax.swing.JMenu();
        VistaCuadicula = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(153, 255, 255));

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel1.setText("Menu Principal");

        MiCuenta.setBackground(new java.awt.Color(51, 255, 255));
        MiCuenta.setText("Mi Cuenta");

        Vender.setBackground(new java.awt.Color(51, 255, 255));
        Vender.setText("Vender");
        Vender.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                VenderActionPerformed(evt);
            }
        });

        Categorias.setBackground(new java.awt.Color(51, 255, 255));
        Categorias.setText("Categorias");
        Categorias.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CategoriasActionPerformed(evt);
            }
        });

        jScrollPane1.setViewportView(nuevoProductoLista);

        jLabel2.setText("Nuevos Productos");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1)
                    .addComponent(MiCuenta)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(Categorias)
                            .addComponent(Vender)
                            .addComponent(jLabel2))
                        .addGap(18, 18, 18)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(22, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addComponent(jLabel1)
                .addGap(37, 37, 37)
                .addComponent(MiCuenta)
                .addGap(30, 30, 30)
                .addComponent(Vender)
                .addGap(27, 27, 27)
                .addComponent(Categorias)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 28, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(21, 21, 21))
        );

        Salir.setText("BuySell");
        Salir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SalirActionPerformed(evt);
            }
        });

        Exit.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_S, java.awt.event.InputEvent.CTRL_MASK));
        Exit.setText("Salir");
        Exit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ExitActionPerformed(evt);
            }
        });
        Salir.add(Exit);

        jMenuBar1.add(Salir);

        MenuCuadricula.setText("View");
        MenuCuadricula.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MenuCuadriculaActionPerformed(evt);
            }
        });

        VistaCuadicula.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_U, java.awt.event.InputEvent.CTRL_MASK));
        VistaCuadicula.setText("Vista Cuadridcula");
        VistaCuadicula.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                VistaCuadiculaActionPerformed(evt);
            }
        });
        MenuCuadricula.add(VistaCuadicula);

        jMenuBar1.add(MenuCuadricula);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void CategoriasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CategoriasActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_CategoriasActionPerformed

    private void VistaCuadiculaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_VistaCuadiculaActionPerformed
        // TODO add your handling code here:
        controlador.CambiarVistaCuadricula();
    }//GEN-LAST:event_VistaCuadiculaActionPerformed

    private void SalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SalirActionPerformed
        // TODO add your handling code here:
        System.exit(0);
    }//GEN-LAST:event_SalirActionPerformed

    private void VenderActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_VenderActionPerformed
        // TODO add your handling code here:
        this.controlador.NuevoProducto();
    }//GEN-LAST:event_VenderActionPerformed

    private void MenuCuadriculaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MenuCuadriculaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_MenuCuadriculaActionPerformed

    private void ExitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ExitActionPerformed
        // TODO add your handling code here:
        System.exit(0);
    }//GEN-LAST:event_ExitActionPerformed

   

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Categorias;
    private javax.swing.JMenuItem Exit;
    private javax.swing.JMenu MenuCuadricula;
    private javax.swing.JButton MiCuenta;
    private javax.swing.JMenu Salir;
    private javax.swing.JButton Vender;
    private javax.swing.JMenuItem VistaCuadicula;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JList nuevoProductoLista;
    // End of variables declaration//GEN-END:variables

    @Override
    public void hacerVisible() {
        this.setVisible(true);
    }

    @Override
    public void noVisible() {
        this.setVisible(false);
    }

    @Override
    public void ErrorUsuario() {
        
    }

    @Override
    public void ErrorContraseña() {
        
    }

    @Override
    public void ErrorDatos() {
        
    }

    @Override
    public void ConfirmarUsuario() {
        
    }

    @Override
    public void colocarNuevoProducto(String s) {
         list.addElement(s);
    }

    @Override
    public void colocarIDUsuario(String idUsuario) {
        
    }
}
